//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoDeTiempoNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<double> horas { get; set; }
        public Nullable<System.DateTime> fechaRealizacion { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public Nullable<byte> servicioRealizado { get; set; }
        public string emailDemandante { get; set; }
        public string emailOfertante { get; set; }
    }
}
